import { describe, expect, it } from "vitest";
import type { ProjectSnapshot } from "../domain/ProjectSnapshot";
import type { Finding } from "../findings/Finding";
import { findingFingerprint } from "../findings/findingFingerprint";
import type { SourceRef } from "../source/SourceRef";
import type { AnalysisContext } from "./AnalysisContext";
import type { ValidationRule } from "./ValidationRule";
import { validateSnapshot } from "./validateSnapshot";

const source: SourceRef = { sourceId: "fixture:test", path: "SDP/Traceability/Relations.yaml", kind: "yaml", pointer: "/slices/SLC-1" };
const context: AnalysisContext = { analyzerVersion: "1", profileId: "sdp", analysisTime: "2026-01-01T00:00:00Z" };
const snapshot: ProjectSnapshot = { profile: { id: "sdp", support: "supported" }, sources: [source], diagnostics: [], entities: [], relations: [], ledger: [] };
function output(ruleId: string, severity: Finding["severity"] = "info", title = ruleId): Finding { return { fingerprint: findingFingerprint(ruleId, [], [source]), ruleId, severity, title, explanation: title, affectedEntityIds: [], sources: [source] }; }

describe("validateSnapshot", () => {
  it("executes rules by stable ID and isolates exceptions", () => { const calls: string[] = []; const rules: ValidationRule[] = [{ id: "SDP003", evaluate: () => { calls.push("3"); return [output("SDP003")]; } }, { id: "SDP001", evaluate: () => { calls.push("1"); throw new Error("boom"); } }, { id: "SDP002", evaluate: () => { calls.push("2"); return [output("SDP002")]; } }]; const result = validateSnapshot(snapshot, context, rules); expect(calls).toEqual(["1", "2", "3"]); expect(result.findings.map((f) => f.ruleId)).toEqual(["SDP002", "SDP003"]); expect(result.diagnostics[0]).toMatchObject({ code: "VALIDATION_RULE_EXCEPTION", message: expect.stringContaining("SDP001") }); });
  it("suppresses duplicate fingerprints and orders findings canonically independent of registry order", () => { const a: ValidationRule = { id: "B", evaluate: () => [output("B", "warning"), output("B", "warning", "changed prose")] }; const b: ValidationRule = { id: "A", evaluate: () => [output("A", "error")] }; expect(validateSnapshot(snapshot, context, [a, b]).findings).toEqual(validateSnapshot(snapshot, context, [b, a]).findings); expect(validateSnapshot(snapshot, context, [a, b]).findings).toHaveLength(2); });
  it("uses structural fingerprints and leaves inputs unchanged", () => { const beforeSnapshot = JSON.stringify(snapshot), beforeContext = JSON.stringify(context); expect(findingFingerprint("X", ["B", "A"], [source])).toBe(findingFingerprint("X", ["A", "B"], [source])); expect(findingFingerprint("X", ["A"], [source])).not.toBe(findingFingerprint("X", ["B"], [source])); const first = validateSnapshot(snapshot, context, []); expect(validateSnapshot(snapshot, context, [])).toEqual(first); expect(JSON.stringify(snapshot)).toBe(beforeSnapshot); expect(JSON.stringify(context)).toBe(beforeContext); });
  it("changes fingerprints when a canonical source location changes", () => { const moved = { ...source, pointer: "/slices/SLC-2" }; expect(findingFingerprint("X", ["SLC-1"], [source])).not.toBe(findingFingerprint("X", ["SLC-1"], [moved])); });
  it("orders by severity and then canonical source location", () => { const earlier = { ...source, pointer: "/a" }, later = { ...source, pointer: "/z" }; const rule: ValidationRule = { id: "ORDER", evaluate: () => [{ ...output("ORDER", "warning"), fingerprint: findingFingerprint("ORDER", [], [later], "later"), sources: [later] }, { ...output("ORDER", "error"), fingerprint: findingFingerprint("ORDER", [], [later], "error"), sources: [later] }, { ...output("ORDER", "warning"), fingerprint: findingFingerprint("ORDER", [], [earlier], "earlier"), sources: [earlier] }] }; const findings = validateSnapshot(snapshot, context, [rule]).findings; expect(findings.map((finding) => finding.severity)).toEqual(["error", "warning", "warning"]); expect(findings.slice(1).map((finding) => finding.sources[0]?.pointer)).toEqual(["/a", "/z"]); });
  it("runs all built-in rules repeatably without mutating snapshot or context", () => { const builtInSnapshot: ProjectSnapshot = { ...snapshot, entities: [{ id: "SLC-1", kind: "slice", status: "completed", attributes: {}, sources: [source] }] }; const beforeSnapshot = structuredClone(builtInSnapshot), beforeContext = structuredClone(context); const first = validateSnapshot(builtInSnapshot, context); expect(validateSnapshot(builtInSnapshot, context)).toEqual(first); expect(builtInSnapshot).toEqual(beforeSnapshot); expect(context).toEqual(beforeContext); });
});
