import { describe, expect, it } from "vitest";
import type { ProjectSnapshot } from "../../domain/ProjectSnapshot";
import type { Diagnostic } from "../../diagnostics/Diagnostic";
import type { Entity } from "../../domain/Entity";
import type { Relation } from "../../domain/Relation";
import type { SourceRef } from "../../source/SourceRef";
import type { ValidationRule } from "../ValidationRule";
import { validateSnapshot } from "../validateSnapshot";
import { completedSliceWithoutVerificationRule, compatibilitySupportRule, contradictoryActiveHierarchyRule, danglingRelationsRule, duplicateEntityDefinitionsRule, malformedLedgerRule, requiredCoreSourcesRule, unresolvedActiveDeclarationsRule } from "./rules";

const s = (pointer = "/"): SourceRef => ({ sourceId: "fixture:broken", path: "SDP/Traceability/Relations.yaml", kind: "yaml", pointer });
const entity = (id: string, kind: string, extra: Partial<Entity> = {}): Entity => ({ id, kind, attributes: {}, sources: [s(`/${id}`)], ...extra });
const relation = (from: string, type: string, to: string): Relation => ({ id: `${from}:${type}:${to}`, from, type, to, sources: [s(`/${from}/${type}`)] });
const snap = (change: Partial<ProjectSnapshot> = {}): ProjectSnapshot => ({ profile: { id: "sdp-tier-1", support: "supported" }, sources: [s()], diagnostics: [], entities: [], relations: [], ledger: [], ...change });
const run = (snapshot: ProjectSnapshot, rule: ValidationRule) => validateSnapshot(snapshot, { analyzerVersion: "1", profileId: "sdp-tier-1", analysisTime: "fixed" }, [rule]).findings;

describe("initial SDP rules", () => {
  it("SDP001 groups duplicate source diagnostics and distinguishes unknown acquisition", () => { const d = (code: string, source = s()): Diagnostic => ({ code, severity: "warning", message: code, source }); expect(run(snap({ diagnostics: [d("DISCOVERY_MISSING_CORE_SOURCE"), d("NORMALIZE_REQUIRED_SOURCE_UNAVAILABLE")] }), requiredCoreSourcesRule)).toHaveLength(1); expect(run(snap({ diagnostics: [d("PARSE_APPLICATION_READ_FAILED")] }), requiredCoreSourcesRule)[0]?.severity).toBe("error"); expect(run(snap({ diagnostics: [{ code: "DISCOVERY_SOURCE_LIST_FAILED", severity: "error", message: "unknown" }] }), requiredCoreSourcesRule)[0]?.severity).toBe("unknown"); });
  it("SDP002 emits one finding with all definition sources and ignores repeated relation targets", () => { const sources = [s("/slices/X"), s("/iterations/X")]; const duplicate = snap({ entities: [{ ...entity("X", "slice"), sources }], diagnostics: sources.map((source) => ({ code: "NORMALIZE_DUPLICATE_ENTITY_DEFINITION", severity: "warning", message: "Entity X has 2 explicit definition keys; every definition location is retained for duplicate analysis.", source })) }); const findings = run(duplicate, duplicateEntityDefinitionsRule); expect(findings).toHaveLength(1); expect(findings[0]?.sources).toHaveLength(2); expect(run(snap({ entities: [entity("A", "slice"), entity("B", "verification")], relations: [relation("A", "verification", "B"), relation("A", "review", "B")] }), duplicateEntityDefinitionsRule)).toEqual([]); });
  it("SDP003 reports each missing endpoint without inventing entities", () => { const snapshot = snap({ entities: [entity("A", "slice")], relations: [relation("A", "review", "B"), relation("C", "review", "A"), relation("A", "review", "A")] }); const findings = run(snapshot, danglingRelationsRule); expect(findings.map((f) => f.title)).toEqual(["Dangling relation to: B", "Dangling relation from: C"]); expect(snapshot.entities.map((e) => e.id)).toEqual(["A"]); });
  it("SDP004 reports malformed and non-object lines while retaining valid neighboring events", () => { const ledgerSource = (lineStart: number) => ({ ...s(), kind: "ndjson" as const, path: "SDP/Traceability/Ledger.ndjson", lineStart, lineEnd: lineStart }); const snapshot = snap({ diagnostics: [{ code: "PARSE_LEDGER_INVALID_JSON", severity: "error", message: "bad JSON", source: ledgerSource(2) }, { code: "PARSE_LEDGER_NON_OBJECT", severity: "error", message: "bad object", source: ledgerSource(4) }], ledger: [{ sequence: 1, eventType: "kept", subjectId: "EVT-1", payload: {}, source: ledgerSource(1) }, { sequence: 3, eventType: "kept", subjectId: "EVT-3", payload: {}, source: ledgerSource(3) }] }); const findings = run(snapshot, malformedLedgerRule); expect(findings).toHaveLength(2); expect(findings.map((finding) => finding.sources[0]?.lineStart)).toEqual([2, 4]); expect(snapshot.ledger.map((event) => event.subjectId)).toEqual(["EVT-1", "EVT-3"]); });
  it("SDP005 handles missing, null, compatible, and incompatible declarations", () => { const active = { sprint: "SPR-X", iteration: "ITR-X", slice: null, source: s("/active"), fieldSources: {} }; expect(run(snap({ active, entities: [entity("ITR-X", "iteration")] }), unresolvedActiveDeclarationsRule).map((f) => f.affectedEntityIds)).toEqual([["SPR-X"]]); expect(run(snap({ active: { ...active, sprint: "ITR-X" }, entities: [entity("ITR-X", "iteration")] }), unresolvedActiveDeclarationsRule)[0]?.explanation).toContain("incompatible"); expect(run(snap({ active: { ...active, sprint: "SPR-X" }, entities: [entity("SPR-X", "sprint"), entity("ITR-X", "iteration")] }), unresolvedActiveDeclarationsRule)).toEqual([]); });
  it("SDP005 reports unresolved active Iteration and Slice independently", () => { const active = { sprint: null, iteration: "ITR-MISSING", slice: "SLC-MISSING", source: s("/active"), fieldSources: {} }; expect(run(snap({ active }), unresolvedActiveDeclarationsRule).map((finding) => finding.affectedEntityIds)).toEqual([["ITR-MISSING"], ["SLC-MISSING"]]); });
  it("SDP006 reports explicit mismatches, including multiple targets, but not absent optional relations", () => { const active = { sprint: "SPR-1", iteration: "ITR-1", slice: "SLC-1", source: s("/active"), fieldSources: {} }; const entities = [entity("SPR-1", "sprint"), entity("ITR-1", "iteration"), entity("SLC-1", "slice")]; expect(run(snap({ active, entities }), contradictoryActiveHierarchyRule)).toEqual([]); const findings = run(snap({ active, entities, relations: [relation("ITR-1", "sprint", "SPR-2"), relation("ITR-1", "sprint", "SPR-3"), relation("SLC-1", "iteration", "ITR-2"), relation("SLC-1", "sprint", "SPR-2")] }), contradictoryActiveHierarchyRule); expect(findings).toHaveLength(3); expect(findings.some((finding) => finding.explanation.includes("SPR-2, SPR-3"))).toBe(true); expect(run(snap({ active, entities, relations: [relation("ITR-1", "sprint", "SPR-1"), relation("SLC-1", "iteration", "ITR-1"), relation("SLC-1", "sprint", "SPR-1")] }), contradictoryActiveHierarchyRule)).toEqual([]); });
  it("SDP007 requires an explicit passed verification entity", () => { const slice = entity("SLC-1", "slice", { status: "completed" }); const base = snap({ entities: [slice] }); expect(run(base, completedSliceWithoutVerificationRule)).toHaveLength(1); const planned = snap({ entities: [slice, entity("VER-1", "verification", { attributes: { outcome: "planned" } })], relations: [relation("SLC-1", "verification_plan", "VER-1")] }); expect(run(planned, completedSliceWithoutVerificationRule)).toHaveLength(1); for (const target of [undefined, entity("VER-1", "review"), entity("VER-1", "verification"), entity("VER-1", "verification", { attributes: { outcome: "failed" } })]) { expect(run(snap({ entities: target ? [slice, target] : [slice], relations: [relation("SLC-1", "verification", "VER-1")] }), completedSliceWithoutVerificationRule)).toHaveLength(1); } expect(run(snap({ entities: [slice, entity("VER-1", "verification", { attributes: { outcome: "passed" } })], relations: [relation("SLC-1", "verification", "VER-1")] }), completedSliceWithoutVerificationRule)).toEqual([]); expect(run(snap({ entities: [entity("SLC-1", "slice", { status: "active" })] }), completedSliceWithoutVerificationRule)).toEqual([]); });
  it("SDP007 does not accept review-only evidence", () => { const slice = entity("SLC-1", "slice", { status: "completed" }); expect(run(snap({ entities: [slice, entity("REV-1", "review")], relations: [relation("SLC-1", "review", "REV-1")] }), completedSliceWithoutVerificationRule)).toHaveLength(1); });
  it.each([["wrong kind", entity("VER-1", "review", { sources: [s("/reviews/VER-1")] })], ["missing outcome", entity("VER-1", "verification", { sources: [s("/verifications/VER-1")] })], ["failed outcome", entity("VER-1", "verification", { attributes: { outcome: "failed" }, sources: [s("/verifications/VER-1")] })]])("SDP007 cites resolved target sources for %s", (_label, target) => { const slice = entity("SLC-1", "slice", { status: "completed" }); const finding = run(snap({ entities: [slice, target], relations: [relation("SLC-1", "verification", "VER-1")] }), completedSliceWithoutVerificationRule)[0]; expect(finding?.sources).toContainEqual(target.sources[0]); });
  it("SDP007 missing targets cite only Slice and relation evidence", () => { const slice = entity("SLC-1", "slice", { status: "completed" }); const verification = relation("SLC-1", "verification", "VER-MISSING"); const finding = run(snap({ entities: [slice], relations: [verification] }), completedSliceWithoutVerificationRule)[0]; expect(finding?.sources).toEqual(expect.arrayContaining([...slice.sources, ...verification.sources])); expect(finding?.sources).toHaveLength(2); });
  it.each([["supported", undefined], ["partial", "warning"], ["unsupported", "error"], ["unknown", "unknown"]] as const)("SDP008 maps %s support", (support, severity) => { const findings = run(snap({ profile: { id: "sdp", support } }), compatibilitySupportRule); if (!severity) expect(findings).toEqual([]); else expect(findings[0]?.severity).toBe(severity); });
});
